### ISSUE TITLE
Feed pharsing problem

### ISSUE THREAD

**Issue by telegrambotdev** [ayrat555/el_monitorro#58] opened 2020-11-25 15:49 UTC
I tried to add one of my feed in the bot

eg url : https://lkhjkjhsdfaughiugfshsfidjojfds.herokuapp.com/?action=display&bridge=Vk&u=zharon&hide_reposts=on&format=Atom

but after i set the correct template,still didnt get the feeds correctly..a single feed content is splitting as each lines.i am adding the attachments below.hope these will help you to understand the problem.

`El_monitoro bot` 👇

`Before i set custom template`

![IMG_20201125_212031_678](https://user-images.githubusercontent.com/20116017/100250962-407b7580-2f64-11eb-9a73-83e116a3f26b.jpg)

`After setting custom Template`

![IMG_20201125_212037_446](https://user-images.githubusercontent.com/20116017/100250918-335e8680-2f64-11eb-8276-4be55e70c8ae.jpg)
![IMG_20201125_212045_290](https://user-images.githubusercontent.com/20116017/100250939-3b1e2b00-2f64-11eb-9fc6-e532eba7a75e.jpg)

![IMG_20201125_213645_913](https://user-images.githubusercontent.com/20116017/100252858-6144ca80-2f66-11eb-9d6f-4ece14dbf1b0.jpg)
https://siftrss.com/f/9Gkky3V77Z

`Another bot with same feed` 👇

![IMG_20201125_212049_627](https://user-images.githubusercontent.com/20116017/100251307-9e0fc200-2f64-11eb-955c-0acdb80f23e4.jpg)

**Comment by telegrambotdev** [comment] 2020-11-25 16:08
could you please fix this ?

**Comment by ayrat555** [comment] 2020-11-25 18:43
@telegrambotdev did you set a template for a feed with `/set_template`, if you did, the template of the feed takes precedence before the global template

**Comment by ayrat555** [comment] 2020-11-25 18:46
I'm not sure I understand the question. You don't want the contents to be split into multiple lines? You can use `bot_space`

**Comment by telegrambotdev** [comment] 2020-11-26 02:32
> I'm not sure I understand the question. You don't want the contents to be split into multiple lines? You can use `bot_space`

Exactly my feed contents are splitting like Feed header in one line,feed content in anotherline etc..

**Comment by telegrambotdev** [comment] 2020-11-26 04:41
> @telegrambotdev did you set a template for a feed with `/set_template`, if you did, the template of the feed takes precedence before the global template

did..now waiting for the next feed updates and i will inform you later.my current feed template is

`/set_template https://lkhjkjhsdfaughiugfshsfidjojfds.herokuapp.com/?action=display&bridge=Vk&u=zharon&hide_reposts=on&format=Atom bot_spacebot_item_namebot_new_linebot_item_description`

**Comment by ayrat555** [comment] 2020-11-26 06:43
@steph9009 I think you should use just `bot_item_namebot_spacebot_item_description`

**Comment by telegrambotdev** [comment] 2020-11-26 06:47
> @steph9009 I think you should use just `bot_item_namebot_spacebot_item_description`

thanks let me try

**Comment by telegrambotdev** [comment] 2020-11-26 08:22
![IMG_20201126_135041_453](https://user-images.githubusercontent.com/20116017/100325302-6f3e2e00-2fee-11eb-9179-ae976679a53b.jpg)


template updated.now i am waiting for the result..once i will get in the correct feeds,i will close this issue.

Thank you

**Comment by ayrat555** [comment] 2020-11-26 08:51
>  i am waiting for the result..once i will get in the correct feeds,i will close this issue.

you can unsubscribe from the feed, subscribe to it again and set the template before you receive any updates. This way you don't have to wait to check if it was updated

**Comment by telegrambotdev** [comment] 2020-11-26 11:28
> > i am waiting for the result..once i will get in the correct feeds,i will close this issue.
> 
> you can unsubscribe from the feed, subscribe to it again and set the template before you receive any updates. This way you don't have to wait to check if the template was updated

Tried.But The messages are getting collapsed like,title is  seperate,description in seperate..

can you check this feed personally for me : https://lkhjkjhsdfaughiugfshsfidjojfds.herokuapp.com/?action=display&bridge=Vk&u=zharon&hide_reposts=on&format=Atom


![IMG_20201126_165551_767](https://user-images.githubusercontent.com/20116017/100345567-80943400-3008-11eb-955f-16d5cc2071fc.jpg) 



![IMG_20201126_165547_501](https://user-images.githubusercontent.com/20116017/100345546-7a05bc80-3008-11eb-8471-f08f6c4c5460.jpg)

**Comment by ayrat555** [comment] 2020-11-26 20:36
I think the issue is the fact that the content of feed items is looks like
```
	<content type="html">Nazwa u&amp;#380;ytkownika: EAV-0283715746 &lt;br&gt;Has&amp;#322;o: km4n7hpscf &lt;br&gt;Klucz licencyjny: P49W-X62U-UCST-H7A7-G7VR &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16/12/2020 &lt;br&gt; &lt;br&gt;&lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283765643 &lt;br&gt;Has&amp;#322;o: 4h28txf7fc &lt;br&gt;Klucz licencyjny: 47XA-X6N5-D4CB-4TMB-UW9V &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16 / 12/2020 &lt;br&gt;EIS &lt;br&gt;klucz licencji: TWK5-XVSK-RA8C-8KB2-A778 &lt;br&gt;data wa&amp;#380;no&amp;#347;ci: 23/02/2021 &lt;br&gt;ESA &lt;br&gt;Nazwa u&amp;#380;ytkownika (login): EAV-0286176431 &lt;br&gt;Has&amp;#322;o: b46vsup34t &lt;br&gt;klucz licencji: F8WD-XSJ3-7RRB-GW5W-VR9W &lt;br&gt;licencji data wa&amp;#380;no&amp;#347;ci: 25/03/2021 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;BWTV-X3KE-2P7W-WDBR-U46H &lt;br&gt;A3T3-XX85-X78G-ESJX-SB63 &lt;br&gt;GTG6-XS88-S48R-NBS8-8SWA &lt;br&gt;EHK7-X4G9-NU9A-PTKX- T35D &lt;br&gt;FPRP-XK7H-TX7W-N2K3-58MS &lt;br&gt;9B3D-X4UK-NAPS-CCBW-M6BF &lt;br&gt;3D4E-XCSP-3SNT-H8CX-BA87 &lt;br&gt; &lt;br&gt;26 listopada 2020 r.Eset &lt;br&gt;Nazwa u&amp;#380;ytkownika i has&amp;#322;o: &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534952 &lt;br&gt;Has&amp;#322;o: fu2jnmhmn4 &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534329 &lt;br&gt;Has&amp;#322;o: 3554tx2343d4f &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika &lt;br&gt;: ukt534m35 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;Первый 2 ключа z 21.01.21 &lt;br&gt; &lt;br&gt;ESET Endpoint Security: &lt;br&gt;HK3V-X3B4-RBP4-6JU7-B3CB &lt;br&gt; &lt;br&gt;Eset Endpoint Antivirus: &lt;br&gt;G4JG-X7R5-T7F9-KMAM-6TRE &lt;br&gt; &lt;br&gt;ESET &lt;br&gt;SB-X5 HXWP -MEK4-45MP (05-11-2021) &lt;br&gt; &lt;br&gt;22.12.2020 JDA7-XTTD-62XP-VMBD-6H4H &lt;br&gt; &lt;br&gt;FA2A-XAT7-N543-GE48-MCT9 &lt;br&gt;Data: 12/02/2021 &lt;br&gt;6EJU-X9FW-FANTS-NV5 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt;CVHS-XGS9-TWVP-8W6X-9E8W &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt; &lt;br&gt;W9X-XAVC-5J2W-6B7A-94MV &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: &lt;br&gt; &lt;br&gt;13.02.2021 X5HR-XEPF-2TKC-4NFT-GRK4 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 14.02.2021</content>
```
I'll try to find a way to fix It on the weekend. Please key you feed running

**Comment by telegrambotdev** [comment] 2020-11-27 02:06
> I think the issue is the fact that the content of feed items is looks like
> 
> ```
> 	<content type="html">Nazwa u&amp;#380;ytkownika: EAV-0283715746 &lt;br&gt;Has&amp;#322;o: km4n7hpscf &lt;br&gt;Klucz licencyjny: P49W-X62U-UCST-H7A7-G7VR &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16/12/2020 &lt;br&gt; &lt;br&gt;&lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283765643 &lt;br&gt;Has&amp;#322;o: 4h28txf7fc &lt;br&gt;Klucz licencyjny: 47XA-X6N5-D4CB-4TMB-UW9V &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16 / 12/2020 &lt;br&gt;EIS &lt;br&gt;klucz licencji: TWK5-XVSK-RA8C-8KB2-A778 &lt;br&gt;data wa&amp;#380;no&amp;#347;ci: 23/02/2021 &lt;br&gt;ESA &lt;br&gt;Nazwa u&amp;#380;ytkownika (login): EAV-0286176431 &lt;br&gt;Has&amp;#322;o: b46vsup34t &lt;br&gt;klucz licencji: F8WD-XSJ3-7RRB-GW5W-VR9W &lt;br&gt;licencji data wa&amp;#380;no&amp;#347;ci: 25/03/2021 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;BWTV-X3KE-2P7W-WDBR-U46H &lt;br&gt;A3T3-XX85-X78G-ESJX-SB63 &lt;br&gt;GTG6-XS88-S48R-NBS8-8SWA &lt;br&gt;EHK7-X4G9-NU9A-PTKX- T35D &lt;br&gt;FPRP-XK7H-TX7W-N2K3-58MS &lt;br&gt;9B3D-X4UK-NAPS-CCBW-M6BF &lt;br&gt;3D4E-XCSP-3SNT-H8CX-BA87 &lt;br&gt; &lt;br&gt;26 listopada 2020 r.Eset &lt;br&gt;Nazwa u&amp;#380;ytkownika i has&amp;#322;o: &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534952 &lt;br&gt;Has&amp;#322;o: fu2jnmhmn4 &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534329 &lt;br&gt;Has&amp;#322;o: 3554tx2343d4f &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika &lt;br&gt;: ukt534m35 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;Первый 2 ключа z 21.01.21 &lt;br&gt; &lt;br&gt;ESET Endpoint Security: &lt;br&gt;HK3V-X3B4-RBP4-6JU7-B3CB &lt;br&gt; &lt;br&gt;Eset Endpoint Antivirus: &lt;br&gt;G4JG-X7R5-T7F9-KMAM-6TRE &lt;br&gt; &lt;br&gt;ESET &lt;br&gt;SB-X5 HXWP -MEK4-45MP (05-11-2021) &lt;br&gt; &lt;br&gt;22.12.2020 JDA7-XTTD-62XP-VMBD-6H4H &lt;br&gt; &lt;br&gt;FA2A-XAT7-N543-GE48-MCT9 &lt;br&gt;Data: 12/02/2021 &lt;br&gt;6EJU-X9FW-FANTS-NV5 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt;CVHS-XGS9-TWVP-8W6X-9E8W &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt; &lt;br&gt;W9X-XAVC-5J2W-6B7A-94MV &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: &lt;br&gt; &lt;br&gt;13.02.2021 X5HR-XEPF-2TKC-4NFT-GRK4 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 14.02.2021</content>
> ```
> 
> I'll try to find a way to fix It on the weekend. Please keep your feed running

Thank you bro 👍

**Comment by telegrambotdev** [comment] 2020-11-27 02:27
> I think the issue is the fact that the content of feed items is looks like
> 
> ```
> 	<content type="html">Nazwa u&amp;#380;ytkownika: EAV-0283715746 &lt;br&gt;Has&amp;#322;o: km4n7hpscf &lt;br&gt;Klucz licencyjny: P49W-X62U-UCST-H7A7-G7VR &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16/12/2020 &lt;br&gt; &lt;br&gt;&lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283765643 &lt;br&gt;Has&amp;#322;o: 4h28txf7fc &lt;br&gt;Klucz licencyjny: 47XA-X6N5-D4CB-4TMB-UW9V &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16 / 12/2020 &lt;br&gt;EIS &lt;br&gt;klucz licencji: TWK5-XVSK-RA8C-8KB2-A778 &lt;br&gt;data wa&amp;#380;no&amp;#347;ci: 23/02/2021 &lt;br&gt;ESA &lt;br&gt;Nazwa u&amp;#380;ytkownika (login): EAV-0286176431 &lt;br&gt;Has&amp;#322;o: b46vsup34t &lt;br&gt;klucz licencji: F8WD-XSJ3-7RRB-GW5W-VR9W &lt;br&gt;licencji data wa&amp;#380;no&amp;#347;ci: 25/03/2021 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;BWTV-X3KE-2P7W-WDBR-U46H &lt;br&gt;A3T3-XX85-X78G-ESJX-SB63 &lt;br&gt;GTG6-XS88-S48R-NBS8-8SWA &lt;br&gt;EHK7-X4G9-NU9A-PTKX- T35D &lt;br&gt;FPRP-XK7H-TX7W-N2K3-58MS &lt;br&gt;9B3D-X4UK-NAPS-CCBW-M6BF &lt;br&gt;3D4E-XCSP-3SNT-H8CX-BA87 &lt;br&gt; &lt;br&gt;26 listopada 2020 r.Eset &lt;br&gt;Nazwa u&amp;#380;ytkownika i has&amp;#322;o: &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534952 &lt;br&gt;Has&amp;#322;o: fu2jnmhmn4 &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534329 &lt;br&gt;Has&amp;#322;o: 3554tx2343d4f &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika &lt;br&gt;: ukt534m35 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;Первый 2 ключа z 21.01.21 &lt;br&gt; &lt;br&gt;ESET Endpoint Security: &lt;br&gt;HK3V-X3B4-RBP4-6JU7-B3CB &lt;br&gt; &lt;br&gt;Eset Endpoint Antivirus: &lt;br&gt;G4JG-X7R5-T7F9-KMAM-6TRE &lt;br&gt; &lt;br&gt;ESET &lt;br&gt;SB-X5 HXWP -MEK4-45MP (05-11-2021) &lt;br&gt; &lt;br&gt;22.12.2020 JDA7-XTTD-62XP-VMBD-6H4H &lt;br&gt; &lt;br&gt;FA2A-XAT7-N543-GE48-MCT9 &lt;br&gt;Data: 12/02/2021 &lt;br&gt;6EJU-X9FW-FANTS-NV5 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt;CVHS-XGS9-TWVP-8W6X-9E8W &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt; &lt;br&gt;W9X-XAVC-5J2W-6B7A-94MV &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: &lt;br&gt; &lt;br&gt;13.02.2021 X5HR-XEPF-2TKC-4NFT-GRK4 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 14.02.2021</content>
> ```
> 
> I'll try to find a way to fix It on the weekend. Please keep your feed running

The feed url which i mentioned above is using  this code for generating feeds

https://github.com/RSS-Bridge/rss-bridge

its a lot of famous..so its better to add support for these feeds.Thanks in Advance

**Comment by telegrambotdev** [comment] 2020-12-04 03:02
> I think the issue is the fact that the content of feed items is looks like
> 
> ```
> 	<content type="html">Nazwa u&amp;#380;ytkownika: EAV-0283715746 &lt;br&gt;Has&amp;#322;o: km4n7hpscf &lt;br&gt;Klucz licencyjny: P49W-X62U-UCST-H7A7-G7VR &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16/12/2020 &lt;br&gt; &lt;br&gt;&lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283765643 &lt;br&gt;Has&amp;#322;o: 4h28txf7fc &lt;br&gt;Klucz licencyjny: 47XA-X6N5-D4CB-4TMB-UW9V &lt;br&gt;wa&amp;#380;no&amp;#347;ci: 16 / 12/2020 &lt;br&gt;EIS &lt;br&gt;klucz licencji: TWK5-XVSK-RA8C-8KB2-A778 &lt;br&gt;data wa&amp;#380;no&amp;#347;ci: 23/02/2021 &lt;br&gt;ESA &lt;br&gt;Nazwa u&amp;#380;ytkownika (login): EAV-0286176431 &lt;br&gt;Has&amp;#322;o: b46vsup34t &lt;br&gt;klucz licencji: F8WD-XSJ3-7RRB-GW5W-VR9W &lt;br&gt;licencji data wa&amp;#380;no&amp;#347;ci: 25/03/2021 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;BWTV-X3KE-2P7W-WDBR-U46H &lt;br&gt;A3T3-XX85-X78G-ESJX-SB63 &lt;br&gt;GTG6-XS88-S48R-NBS8-8SWA &lt;br&gt;EHK7-X4G9-NU9A-PTKX- T35D &lt;br&gt;FPRP-XK7H-TX7W-N2K3-58MS &lt;br&gt;9B3D-X4UK-NAPS-CCBW-M6BF &lt;br&gt;3D4E-XCSP-3SNT-H8CX-BA87 &lt;br&gt; &lt;br&gt;26 listopada 2020 r.Eset &lt;br&gt;Nazwa u&amp;#380;ytkownika i has&amp;#322;o: &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534952 &lt;br&gt;Has&amp;#322;o: fu2jnmhmn4 &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika: EAV-0283534329 &lt;br&gt;Has&amp;#322;o: 3554tx2343d4f &lt;br&gt; &lt;br&gt;Nazwa u&amp;#380;ytkownika &lt;br&gt;: ukt534m35 &lt;br&gt; &lt;br&gt;- - - Zaktualizowano - - - &lt;br&gt; &lt;br&gt;Первый 2 ключа z 21.01.21 &lt;br&gt; &lt;br&gt;ESET Endpoint Security: &lt;br&gt;HK3V-X3B4-RBP4-6JU7-B3CB &lt;br&gt; &lt;br&gt;Eset Endpoint Antivirus: &lt;br&gt;G4JG-X7R5-T7F9-KMAM-6TRE &lt;br&gt; &lt;br&gt;ESET &lt;br&gt;SB-X5 HXWP -MEK4-45MP (05-11-2021) &lt;br&gt; &lt;br&gt;22.12.2020 JDA7-XTTD-62XP-VMBD-6H4H &lt;br&gt; &lt;br&gt;FA2A-XAT7-N543-GE48-MCT9 &lt;br&gt;Data: 12/02/2021 &lt;br&gt;6EJU-X9FW-FANTS-NV5 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt;CVHS-XGS9-TWVP-8W6X-9E8W &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 02.12.2021 &lt;br&gt; &lt;br&gt;W9X-XAVC-5J2W-6B7A-94MV &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: &lt;br&gt; &lt;br&gt;13.02.2021 X5HR-XEPF-2TKC-4NFT-GRK4 &lt;br&gt;Wa&amp;#380;no&amp;#347;&amp;#263;: 14.02.2021</content>
> ```
> 
> I'll try to find a way to fix It on the weekend. Please keep your feed running

did you fixed that bro ?

**Comment by ayrat555** [comment] 2020-12-04 06:11
The previous week I was improving delivery logic.
I hope I'll find some time to work on this issue this weekend

**Comment by ayrat555** [comment] 2020-12-13 17:22
@telegrambotdev I merged a fix. Can you please check if it works for you?

**Closed** 2020-12-13 17:22 UTC

**Comment by telegrambotdev** [comment] 2020-12-19 02:18
yes working
